swagger: "2.0"
info:
  title: Safe Vault API
  description: This API allows customers to create , transfer and receive money and also do other banking transactions
  version: 1.0.0
host: localhost:9639
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
#paths:

  
